source 'https://ruby.taobao.org'

gem 'activesupport'
gem 'faraday', '~> 0.11.0'
gem 'pry'
gem 'slop'
gem 'selenium-webdriver', '~> 3.1'
gem 'rollbar'
gem 'sucker_punch', '~> 1.6'
gem 'mailgun-ruby', '~> 1.1'
gem 'faraday_middleware', '~> 0.10.0'
gem 'nokogiri', '~> 1.6', '>= 1.6.8'
